# Generated by Django 5.2.16 on 2026-07-28 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoria de material',
                'verbose_name_plural': 'categorias de materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='fonte_importacao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='material',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='material',
            name='importado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='url_origem',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='cadastros.categoriamaterial'),
        ),
    ]
