# Generated by Django 5.2.16 on 2026-07-28 08:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_eletricista', models.CharField(blank=True, max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('validade_padrao_dias', models.PositiveIntegerField(default=15)),
                ('valor_hora_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentual_ferramentas', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentual_empresa', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentual_lucro', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mostrar_deslocamento_proposta', models.BooleanField(default=False)),
                ('observacao_cliente_padrao', models.TextField(blank=True)),
                ('observacao_interna_padrao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
            },
        ),
    ]
