# Generated by Django 5.2.16 on 2026-07-28 08:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseProdutividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('data', models.DateField()),
                ('cliente_obra', models.CharField(blank=True, max_length=200)),
                ('valor_total_cobrado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_materiais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_deslocamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('outros_custos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_base_mao_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('horas_homem_total', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=14)),
                ('valor_hora_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'análise de produtividade',
                'verbose_name_plural': 'análises de produtividade',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=160)),
                ('unidade', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tempo_horas', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantidade_pessoas', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('horas_homem', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=14)),
                ('produtividade', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14)),
                ('tempo_por_unidade', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14)),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_unitario_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacoes', models.CharField(blank=True, max_length=250)),
                ('altura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.trabalhoaltura')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ferramentas.analiseprodutividade')),
                ('dificuldade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.dificuldade')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.servico')),
            ],
            options={
                'verbose_name': 'item executado',
                'verbose_name_plural': 'itens executados',
            },
        ),
    ]
