# Generated by Django 5.2.16 on 2026-07-28 08:34

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('validade', models.DateField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='rascunho', max_length=15)),
                ('cliente_nome', models.CharField(max_length=160, verbose_name='nome do cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone do cliente')),
                ('endereco_obra', models.CharField(blank=True, max_length=250)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('custo_deslocamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('metodo_mao_obra', models.CharField(choices=[('servicos', 'Por serviços lançados'), ('tempo', 'Por tempo estimado × valor hora')], default='servicos', max_length=15)),
                ('tempo_estimado_horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_hora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentual_ferramentas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentual_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentual_lucro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes_internas', models.TextField(blank=True)),
                ('observacoes_cliente', models.TextField(blank=True)),
                ('subtotal_materiais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal_insumos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal_servicos_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_dificuldade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_altura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal_servicos_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outros_custos_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('custos_diretos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserva_ferramentas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal_operacional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserva_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal_antes_lucro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.veiculo')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFornecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('unidade', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fornecedor', models.CharField(blank=True, max_length=160)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.material')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_fornecidos', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'material fornecido',
                'verbose_name_plural': 'materiais fornecidos',
            },
        ),
        migrations.CreateModel(
            name='MaterialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidade', models.CharField(max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=250)),
                ('material_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.material')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_cliente', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'material para o cliente',
                'verbose_name_plural': 'materiais para o cliente',
            },
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('unidade', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_dificuldade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_altura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('altura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.trabalhoaltura')),
                ('dificuldade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.dificuldade')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.servico')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'serviço do orçamento',
                'verbose_name_plural': 'serviços do orçamento',
            },
        ),
        migrations.CreateModel(
            name='InsumoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('unidade', models.CharField(max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.material')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_internos', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'insumo interno',
                'verbose_name_plural': 'insumos internos',
            },
        ),
        migrations.CreateModel(
            name='OutroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outros_custos', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'outro custo',
                'verbose_name_plural': 'outros custos',
            },
        ),
    ]
