# Generated by Django 5.2.16 on 2026-07-28 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
